apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
#can be used by single node
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
